import { Regex } from '@companion-module/base'

export function getConfigFields() {
	return [
		{
			type: 'static-text',
			id: 'info',
			width: 12,
			label: 'Tenveo PTZ',
			value:
				'Controls Tenveo PTZ cameras over VISCA (TCP/UDP) for PTZ + image, and ONVIF for presets ' +
				'(needed on Tenveo NDI models that silently drop VISCA preset commands).',
		},
		{
			type: 'textinput',
			id: 'name',
			label: 'Camera Name',
			width: 6,
			default: 'Tenveo Camera',
		},
		{
			type: 'textinput',
			id: 'host',
			label: 'IP Address',
			width: 6,
			default: '192.168.88.11',
			regex: Regex.IP,
		},
		{
			type: 'dropdown',
			id: 'transport',
			label: 'VISCA Protocol',
			width: 6,
			default: 'tcp',
			choices: [
				{ id: 'tcp', label: 'TCP (recommended)' },
				{ id: 'udp', label: 'UDP — VISCA-over-IP' },
			],
		},
		{
			type: 'number',
			id: 'port',
			label: 'VISCA Port (Tenveo uses 52381 for both)',
			width: 3,
			default: 52381,
			min: 1,
			max: 65535,
		},
		{
			type: 'number',
			id: 'cameraId',
			label: 'Camera ID (1-7)',
			width: 3,
			default: 1,
			min: 1,
			max: 7,
		},
		{
			type: 'static-text',
			id: 'onvif_info',
			width: 12,
			label: 'ONVIF (presets)',
			value:
				'Tenveo NDI firmware exposes preset save/recall only via ONVIF. Default ONVIF credentials are admin / admin.',
		},
		{
			type: 'number',
			id: 'onvifPort',
			label: 'ONVIF Port',
			width: 3,
			default: 2000,
			min: 1,
			max: 65535,
		},
		{
			type: 'textinput',
			id: 'onvifUser',
			label: 'ONVIF Username',
			width: 3,
			default: 'admin',
		},
		{
			type: 'textinput',
			id: 'onvifPass',
			label: 'ONVIF Password',
			width: 3,
			default: 'admin',
		},
		{
			type: 'number',
			id: 'panSpeed',
			label: 'Default Pan Speed (1-24)',
			width: 3,
			default: 12,
			min: 1,
			max: 24,
		},
		{
			type: 'number',
			id: 'tiltSpeed',
			label: 'Default Tilt Speed (1-20)',
			width: 3,
			default: 10,
			min: 1,
			max: 20,
		},
		{
			type: 'number',
			id: 'zoomSpeed',
			label: 'Default Zoom Speed (0-7)',
			width: 3,
			default: 4,
			min: 0,
			max: 7,
		},
		{
			type: 'number',
			id: 'unitsPerDegree',
			label: 'VISCA units per degree (Standard STEP calibration)',
			width: 3,
			default: 14,
			min: 1,
			max: 200,
		},
		{
			type: 'number',
			id: 'msPerDegree',
			label: 'ms per degree (NDI drive-pulse STEP calibration)',
			width: 3,
			default: 80,
			min: 10,
			max: 1000,
		},
		{
			type: 'number',
			id: 'pollInterval',
			label: 'Polling Interval (ms, 0 disables)',
			width: 3,
			default: 0,
			min: 0,
			max: 60000,
		},
		{
			type: 'checkbox',
			id: 'verbose',
			label: 'Verbose Logging',
			width: 6,
			default: false,
		},
	]
}
