import { Regex } from '@companion-module/base'

export function getConfigFields() {
	return [
		{
			type: 'static-text',
			id: 'info',
			width: 12,
			label: 'Tenveo PTZ',
			value:
				'Controls Tenveo PTZ cameras over VISCA (TCP/UDP) for PTZ + image, and ONVIF for presets ' +
				'(needed on Tenveo NDI models that silently drop VISCA preset commands).',
		},
		{
			type: 'textinput',
			id: 'name',
			label: 'Camera Name',
			width: 6,
			default: 'Tenveo Camera',
		},
		{
			type: 'textinput',
			id: 'host',
			label: 'IP Address',
			width: 6,
			default: '192.168.88.11',
			regex: Regex.IP,
		},
		{
			type: 'dropdown',
			id: 'variant',
			label: 'Camera Variant',
			width: 12,
			default: 'standard',
			choices: [
				{ id: 'standard', label: 'Standard (VHD20H-U / non-NDI)' },
				{ id: 'ndi', label: 'NDI Quirks (VHD20HAN / NDI)' },
			],
		},
		{
			type: 'dropdown',
			id: 'transport',
			label: 'VISCA Protocol',
			width: 6,
			default: 'tcp',
			choices: [
				{ id: 'tcp', label: 'TCP (recommended)' },
				{ id: 'udp', label: 'UDP — VISCA-over-IP' },
			],
		},
		{
			type: 'number',
			id: 'port',
			label: 'VISCA Port (Tenveo uses 52381 for both)',
			width: 3,
			default: 52381,
			min: 1,
			max: 65535,
		},
		{
			type: 'number',
			id: 'cameraId',
			label: 'Camera ID (1-7)',
			width: 3,
			default: 1,
			min: 1,
			max: 7,
		},
		{
			type: 'static-text',
			id: 'onvif_info',
			width: 12,
			label: 'ONVIF (presets)',
			value:
				'Tenveo NDI firmware exposes preset save/recall only via ONVIF. Default ONVIF credentials are admin / admin.',
		},
		{
			type: 'number',
			id: 'onvifPort',
			label: 'ONVIF Port',
			width: 3,
			default: 2000,
			min: 1,
			max: 65535,
		},
		{
			type: 'textinput',
			id: 'onvifUser',
			label: 'ONVIF Username',
			width: 3,
			default: 'admin',
		},
		{
			type: 'textinput',
			id: 'onvifPass',
			label: 'ONVIF Password',
			width: 3,
			default: 'admin',
		},
		{
			type: 'number',
			id: 'panSpeed',
			label: 'Default Pan Speed (1-24)',
			width: 3,
			default: 12,
			min: 1,
			max: 24,
		},
		{
			type: 'number',
			id: 'tiltSpeed',
			label: 'Default Tilt Speed (1-20)',
			width: 3,
			default: 10,
			min: 1,
			max: 20,
		},
		{
			type: 'number',
			id: 'zoomSpeed',
			label: 'Default Zoom Speed (0-7)',
			width: 3,
			default: 4,
			min: 0,
			max: 7,
		},
		{
			type: 'number',
			id: 'unitsPerDegree',
			label: 'VISCA units per degree (Standard STEP calibration)',
			width: 3,
			default: 14,
			min: 1,
			max: 200,
		},
		{
			type: 'number',
			id: 'panDegPerSec',
			label: 'Pan °/s @ speed 24 (HOLD tracking calibration)',
			width: 3,
			default: 100,
			min: 1,
			max: 400,
		},
		{
			type: 'number',
			id: 'tiltDegPerSec',
			label: 'Tilt °/s @ speed 20 (HOLD tracking calibration)',
			width: 3,
			default: 60,
			min: 1,
			max: 400,
		},
		{
			type: 'static-text',
			id: 'stepCalibInfo',
			width: 12,
			label: 'Rotary STEP absolute-position calibration',
			value:
				'Rotary STEP Pan/Tilt uses ptAbsolute with these values. Defaults match the user-calibrated NDI ' +
				'VHD20HAN (center 19050/8000, 108.74 pan units/°, 86.66 tilt units/°). If the camera moves the ' +
				'wrong direction, flip the sign of Pan/Tilt units per degree.',
		},
		{
			type: 'number',
			id: 'panCenter',
			label: 'Pan center (raw VISCA units at 0°)',
			width: 3,
			default: 19050,
			min: -32768,
			max: 32767,
		},
		{
			type: 'number',
			id: 'panUnitsPerDeg',
			label: 'Pan units per degree (signed; flip sign to invert)',
			width: 3,
			default: 108.74,
			min: -500,
			max: 500,
			step: 0.01,
		},
		{
			type: 'number',
			id: 'panMinDeg',
			label: 'Pan LEFT limit (degrees)',
			width: 3,
			default: -175,
			min: -360,
			max: 0,
		},
		{
			type: 'number',
			id: 'panMaxDeg',
			label: 'Pan RIGHT limit (degrees)',
			width: 3,
			default: 175,
			min: 0,
			max: 360,
		},
		{
			type: 'number',
			id: 'tiltCenter',
			label: 'Tilt center (raw VISCA units at 0°)',
			width: 3,
			default: 8000,
			min: -32768,
			max: 32767,
		},
		{
			type: 'number',
			id: 'tiltUnitsPerDeg',
			label: 'Tilt units per degree (signed; flip sign to invert)',
			width: 3,
			default: 86.66,
			min: -500,
			max: 500,
			step: 0.01,
		},
		{
			type: 'number',
			id: 'tiltMinDeg',
			label: 'Tilt DOWN limit (degrees)',
			width: 3,
			default: -90,
			min: -180,
			max: 0,
		},
		{
			type: 'number',
			id: 'tiltMaxDeg',
			label: 'Tilt UP limit (degrees)',
			width: 3,
			default: 90,
			min: 0,
			max: 180,
		},
		{
			type: 'number',
			id: 'pollInterval',
			label: 'Polling Interval (ms, 0 disables)',
			width: 3,
			default: 0,
			min: 0,
			max: 60000,
		},
		{
			type: 'checkbox',
			id: 'verbose',
			label: 'Verbose Logging',
			width: 6,
			default: false,
		},
	]
}
